name: Rust Linux

on:
  release:
    types: [ published ]
    
env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install gdk-3
      run: sudo apt-get install -y libgtk-3-dev
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --release --verbose
    - name: Save artifacts
      uses: actions/upload-artifact@v3
      with:
        name: executable
        path: target/release/splinter
